//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net.Appclusive.WPF.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Net.Appclusive.WPF.UI.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occurred..
        /// </summary>
        internal static string App_CurrentDomain_UnhandledException__UnhandledExceptionOccurred {
            get {
                return ResourceManager.GetString("App_CurrentDomain_UnhandledException__UnhandledExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Appclusive WPF UI ....
        /// </summary>
        internal static string App_OnExit__START {
            get {
                return ResourceManager.GetString("App_OnExit__START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Appclusive WPF UI SUCCEEDED..
        /// </summary>
        internal static string App_OnExit__SUCCEEDED {
            get {
                return ResourceManager.GetString("App_OnExit__SUCCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appclusive WPF UI configuration (DefaultDomain: &apos;{0}&apos;; AppclusiveApiBaseUri: &apos;{1}&apos;) SUCCEEDED..
        /// </summary>
        internal static string App_OnStartup__Initialise_Configuration {
            get {
                return ResourceManager.GetString("App_OnStartup__Initialise_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appclusive WPF UI initialisation ....
        /// </summary>
        internal static string App_OnStartup__Initialise_START {
            get {
                return ResourceManager.GetString("App_OnStartup__Initialise_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appclusive WPF UI initialisation SUCCEEDED..
        /// </summary>
        internal static string App_OnStartup__Initialise_SUCCEEDED {
            get {
                return ResourceManager.GetString("App_OnStartup__Initialise_SUCCEEDED", resourceCulture);
            }
        }
    }
}
