//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net.Appclusive.WPF.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Net.Appclusive.WPF.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArbitraryValue1.
        /// </summary>
        internal static string ArbitraryEnum_Value1 {
            get {
                return ResourceManager.GetString("ArbitraryEnum_Value1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPF UI for the Appclusive Blueprint Modelling and Automation Engine
        ///
        ///Version: {0}
        ///
        ///
        ///d-fens GmbH
        ///General-Guisan-Strasse 6
        ///CH-6300 Zug
        ///Switzerland.
        /// </summary>
        internal static string Dialog_About__Message {
            get {
                return ResourceManager.GetString("Dialog_About__Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über.
        /// </summary>
        internal static string Dialog_About__Title {
            get {
                return ResourceManager.GetString("Dialog_About__Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        internal static string Page_Home_Label__Domain {
            get {
                return ResourceManager.GetString("Page_Home_Label__Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        internal static string Page_Home_Label__Password {
            get {
                return ResourceManager.GetString("Page_Home_Label__Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Page_Home_Label__Username {
            get {
                return ResourceManager.GetString("Page_Home_Label__Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Page_Home_Title {
            get {
                return ResourceManager.GetString("Page_Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über.
        /// </summary>
        internal static string Window_MainWindow_Button__About {
            get {
                return ResourceManager.GetString("Window_MainWindow_Button__About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appclusive WPF UI.
        /// </summary>
        internal static string Window_MainWindow_Title {
            get {
                return ResourceManager.GetString("Window_MainWindow_Title", resourceCulture);
            }
        }
    }
}
